# =========================================================================================================
# ============================== DO NOT MAKE ANY CHANGES TO THIS FILE =====================================
# =========================================================================================================
# Esse arquivo não deverá ser alterado sem autorização prévia e uma revisão adequada da equipe
# Não export esse arquivo para evitar comprometer a integridade e segurança da aplicação

services:
  laravel12-template:
    build:
      context: ./docker/develop
      dockerfile: Dockerfile
    image: laravel12-template-app
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${APP_PORT:-80}:80
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    environment:
      MYSQL_HOST: ${DB_HOST:-mysql}
      XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-develop,debug,coverage}
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - .:/var/www/html
    networks:
      - laravel12-template-network

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE:-laravel12_template_db}
      MYSQL_USER: ${DB_USERNAME:-laravel12_template}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - laravel12-template-mysql-vol:/var/lib/mysql
    networks:
      - laravel12-template-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT:-8888}:80
    environment:
      - PMA_HOST=${DB_HOST:-mysql}
      - PMA_PORT=${DB_PORT:-3306}
      - PMA_USER=${DB_USERNAME:-root}
      - PMA_PASSWORD=${DB_PASSWORD:-root}
    networks:
      - laravel12-template-network
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - laravel12-template-redis-vol:/data
    networks:
      - laravel12-template-network

  redis-cmd:
    image: rediscommander/redis-commander:latest
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    networks:
      - laravel12-template-network
    depends_on:
      - redis

  minio:
    image: minio/minio:latest
    ports:
      - ${FORWARD_MINIO_PORT:-9000}:9000
      - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-laravel12-template}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-laravel12-template}
    command: 'minio server /data --console-address ":8900"'
    volumes:
      - laravel12-template-minio-vol:/data
    networks:
      - laravel12-template-network

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
    networks:
      - laravel12-template-network

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    environment:
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID:-null}
      SOKETI_DEFAULT_APP_KEY: ${PUSHER_APP_KEY:-null}
      SOKETI_DEFAULT_APP_SECRET: ${PUSHER_APP_SECRET:-null}
    ports:
      - ${PUSHER_PORT:-6001}:6001
      - ${PUSHER_METRICS_PORT:-9601}:9601
    networks:
      - laravel12-template-network

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - ${FORWARD_MEILISEARCH_PORT:-7700}:7700
    volumes:
      - laravel12-template-meilisearch-vol:/meili_data
    networks:
      - laravel12-template-network

  selenium:
    image: selenium/standalone-chromium
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - laravel12-template-network

networks:
  laravel12-template-network:
    driver: bridge

volumes:
  laravel12-template-mysql-vol:
    driver: local
  laravel12-template-redis-vol:
    driver: local
  laravel12-template-minio-vol:
    driver: local
  laravel12-template-meilisearch-vol:
    driver: local
