services:
  laravel12-template:
    build:
      context: ./docker/develop
      dockerfile: Dockerfile
    image: laravel12-template-app
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${APP_PORT:-80}:80
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
      - ${XDEBUG_PORT:-9003}:${XDEBUG_PORT:-9003}
    environment:
      WWWUSER: 1000
      WWWGROUP: 1000
      TZ: ${APP_TZ:-America/Recife}
      DB_HOST: ${DB_HOST:-mysql}
      DB_USER: ${DB_USERNAME:-laravel12_template}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-develop,debug,coverage}
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - .:/var/www
    networks:
      - laravel12-template-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE:-laravel12_template_db}
      MYSQL_USER: ${DB_USERNAME:-laravel12_template}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - laravel12-template-mysql-vol:/var/lib/mysql
    networks:
      - laravel12-template-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-root}"]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - laravel12-template-redis-vol:/data
    networks:
      - laravel12-template-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  minio:
    image: minio/minio:latest
    ports:
      - ${FORWARD_MINIO_PORT:-9000}:9000
      - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-laravel12-template}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-laravel12-template}
    command: 'minio server /data --console-address ":8900"'
    volumes:
      - laravel12-template-minio-vol:/data
    networks:
      - laravel12-template-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      retries: 3
      timeout: 5s

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
    networks:
      - laravel12-template-network

networks:
  laravel12-template-network:
    driver: bridge

volumes:
  laravel12-template-mysql-vol:
    driver: local
  laravel12-template-redis-vol:
    driver: local
  laravel12-template-minio-vol:
    driver: local
