services:
  laravel12-template-production:
    build:
      context: ./docker/production
      dockerfile: Dockerfile
    image: laravel12-template-production:v1
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .:/var/www

networks:
  laravel12-template-network:
    driver: bridge
    external: true
